### ISSUE TITLE
Deprecation warning with webpack 4

### ISSUE THREAD

**Issue by tzimmermann** [tomchentw/unused-files-webpack-plugin#22]
Using`webpack 4.1.1`, I get this warning during webpack build:

`
(node:40693) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
`

With help of https://github.com/webpack/webpack/issues/6568#issuecomment-373679018, I was able to trace the culprit to being the `unused-files-webpack-plugin`:

`
    at UnusedFilesWebpackPlugin.apply (/Users/tz-mac/Repos/pex-client/node_modules/unused-files-webpack-plugin/lib/index__8.0.0__.js:105:14)
    at webpack (/Users/tz-mac/Repos/pex-client/node_modules/webpack/lib/webpack.js:37:12)
`

which refers to this line: https://github.com/tomchentw/unused-files-webpack-plugin/blob/e63a89caa2c4564134e56ee2c57cc435cd76363a/lib/index__8.0.0__.js#L105

**Comment by oising** [comment]
Yeah, I had a similar issue in a `build.ts` used in the `aurelia-cli` build tasks. I know nothing about webpack internals, but I figured out enough to switch from using `compiler.plugin('done', ...) ` to `compiler.hooks.done.tap('done', ...)` Your mileage may vary. Here's my code in context:
```
function buildWebpack(done) {
  if (CLIOptions.hasFlag('watch')) {
    compiler.watch({}, onBuild);
  } else {
    compiler.run(onBuild);
    //compiler.plugin('done', () => done());
    compiler.hooks.done.tap('done', () => done());
  }
}
```

**Comment by oising** [comment]
fyi, there is a `compiler.hooks.afterEmit` hook ;)

**Comment by Akiyamka** [comment]
Any chance this will be fixed?
